services:
  - type: web
    name: image-compressor
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    env: 
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
    autoDeploy: true
